@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NTgzNDQ4NTV9.wJ6gfB_BwrZ96C1gPhmtdq8ABAw8gNNQG2Ln48yFOto

POST http://localhost:3000/users
Content-Type: application/json

{
  "first_name": "Ben",
  "last_name": "J",
  "email": "ben@gmail.com",
  "password": "password",
  "birthdate": "1987-12-18"
}

###
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "ben@gmail.com",
  "password": "password"
}

###
GET http://localhost:3000/users/2/remedies.json
Authorization: Bearer {{jwt}}

###
GET http://localhost:3000/users/2/remedies/2.json
Authorization: Bearer {{jwt}}